// Margulis-Mozes Theorem 5 polygon tiling — Poincare disc model.
//
// Reference: Margulis & Mozes, "Aperiodic Tilings of the Hyperbolic Plane
// by Convex Polygons", Israel J. Math. 107 (1998), 319–325.
//
// Theorem 5: For n >= 5 and any a > 0, the polygon P_a with vertices
//   A_j = (j-1)a + i,  1 <= j <= n-2,
//   A_{n-1} = (n-3)a + (n-3)i,
//   A_n = (n-3)i
// tiles H^2 via the semigroup generated by Tz = z/(n-3), S_a z = z ± (n-3)a.
//
// This shader maps from the Poincare disc to UHP via Cayley transform,
// then runs the tiling algorithm in UHP coordinates.

#ifdef GL_ES
precision highp float;
#endif

#ifdef GL_OES_standard_derivatives
#extension GL_OES_standard_derivatives : enable
#endif

uniform vec2  uResolution;
uniform float uThickness;   // Hyperbolic edge line width
uniform float uChildren;    // Branching factor m = n-3 (>= 2)
uniform float uParam;       // Vertex spacing parameter a (> 0)
varying vec2  vPos;

#define MAX_CHILDREN 16

vec3 color4(int id){
  if(id==0) return vec3(0.93,0.40,0.40);
  if(id==1) return vec3(0.42,0.72,0.98);
  if(id==2) return vec3(0.52,0.92,0.56);
  return vec3(0.95,0.86,0.45);
}

vec2 cdiv(vec2 a, vec2 b){
  float d = dot(b,b);
  return vec2((a.x*b.x+a.y*b.y)/d, (a.y*b.x-a.x*b.y)/d);
}

float asinh1(float x){
  return log(x + sqrt(x*x + 1.0));
}

float signedDistGeodesic(float ea, float eb, vec2 z){
  float c = 0.5*(ea + eb);
  float r = 0.5*abs(eb - ea);
  float dx = z.x - c;
  return asinh1((dx*dx + z.y*z.y - r*r) / (2.0 * r * max(z.y, 1e-6)));
}

float distToVertical(float x0, vec2 z){
  return asinh1(abs(z.x - x0) / max(z.y, 1e-6));
}

void main(){
  float m  = max(uChildren, 2.0);
  float a  = max(uParam, 0.01);
  float hw = max(uThickness, 0.001);
  float logB = log2(m);
  float tW = m * a;

  vec2 R  = uResolution;
  vec2 uv = (vPos*0.5+0.5)*R;
  vec2 s  = (2.0*uv - R)/R.y;

  float r2 = dot(s,s);
  vec3 col = vec3(1.0);

  if(r2 < 1.0){
    // ── Poincare disc -> UHP via Cayley transform ──
    vec2 z   = s;
    vec2 num = vec2(1.0+z.x,  z.y);
    vec2 den = vec2(1.0-z.x, -z.y);
    vec2 w   = cdiv(num, den);          // (1+z)/(1-z)
    vec2 zeta= vec2(-w.y, w.x);        // multiply by i

    float x = zeta.x, y = zeta.y;

    float eps = max(1e-6, fwidth(y));
    float yC  = max(y, eps);
    int   n = int(floor(log2(yC)/logB));
    float K = pow(m, float(-n));

    // Renormalized coords
    float xren = K*x;
    float yren = K*y;
    float cell = floor(xren/tW);
    float xmod = xren - cell*tW;
    float ymod = yren;

    float yOrig = yren;
    float xmodOrig = xmod;

    // ── Cap geometry ──
    float rb2 = a*a*0.25 + 1.0;
    float r0  = sqrt(rb2);

    bool  under = false;
    float dCap  = 1e10;

    for(int k = 0; k < MAX_CHILDREN; k++){
      if(float(k) >= m) break;
      float ck = (float(k)+0.5)*a;
      float dx = xmod - ck;
      float d2 = dx*dx + ymod*ymod;
      if(d2 < rb2) under = true;

      float ga = ck - r0, gb = ck + r0;
      float d  = abs(signedDistGeodesic(ga, gb, vec2(xmod, ymod)));
      dCap = min(dCap, d);
    }

    if(under){
      n -= 1;
      K = pow(m, float(-n));
      xren = K*x;
      yren = K*y;
      cell = floor(xren/tW);
      xmod = xren - cell*tW;
    }

    // ── 4-coloring ──
    int h  = -n;
    int l  = int(cell);
    int pN = int(mod(float(h)+4096.0, 2.0));
    int pL = int(mod(float(l)+4096.0, 2.0));
    int id = pN*2 + pL;
    vec3 tc = color4(id);

    // Fade near y = 0 (match UHP rendering order)
    float fade = smoothstep(0.0, 3.0*eps, y);
    col = mix(vec3(1.0), tc, fade);

    // ── Edge lines ──

    // Top edge: geodesic from (0, m) to (tW, m) in pre-cap cell coords
    float topR  = sqrt(tW*tW*0.25 + m*m);
    float dTop  = abs(signedDistGeodesic(tW*0.5-topR, tW*0.5+topR, vec2(xmodOrig, yOrig)));
    float pwTop = fwidth(dTop);
    float lTop  = 1.0 - smoothstep(hw-pwTop, hw+pwTop, dTop);

    float dV  = min(distToVertical(0.0, vec2(xmod, yren)),
                    distToVertical(tW,  vec2(xmod, yren)));
    float pwV = fwidth(dV);
    float lV  = 1.0 - smoothstep(hw-pwV, hw+pwV, dV);

    // Bottom bumps: geodesic distance to cap arcs
    float pwC = fwidth(dCap);
    float lC  = 1.0 - smoothstep(hw-pwC, hw+pwC, dCap);

    float line = max(max(lTop, lV), lC);
    col = mix(col, vec3(0.15), line*fade);

    // Disc boundary
    float dr = 1.0 - sqrt(r2);
    float px = fwidth(s.x) + fwidth(s.y);
    float edge = smoothstep(0.0, 2.0*px, dr);
    col = mix(vec3(1.0), col, edge);
  }

  gl_FragColor = vec4(col, 1.0);
}
