// Margulis-Mozes Theorem 5 polygon tiling — Upper Half-Plane model.
//
// Reference: Margulis & Mozes, "Aperiodic Tilings of the Hyperbolic Plane
// by Convex Polygons", Israel J. Math. 107 (1998), 319–325.
//
// Theorem 5: For n >= 5 and any a > 0, the polygon P_a with vertices
//   A_j = (j-1)a + i,  1 <= j <= n-2,
//   A_{n-1} = (n-3)a + (n-3)i,
//   A_n = (n-3)i
// tiles H^2 via the semigroup generated by Tz = z/(n-3), S_a z = z ± (n-3)a.
// For almost every a > 0 the tiling system is aperiodic.

#ifdef GL_ES
precision highp float;
#endif

#ifdef GL_OES_standard_derivatives
#extension GL_OES_standard_derivatives : enable
#endif

uniform vec2  uResolution;
uniform float uThickness;   // Hyperbolic edge line width
uniform float uChildren;    // Branching factor m = n-3 (>= 2)
uniform float uParam;       // Vertex spacing parameter a (> 0)
varying vec2  vPos;

#define MAX_CHILDREN 16

vec3 color4(int id){
  if(id==0) return vec3(0.93,0.40,0.40);
  if(id==1) return vec3(0.42,0.72,0.98);
  if(id==2) return vec3(0.52,0.92,0.56);
  return vec3(0.95,0.86,0.45);
}

vec2 toWorld(vec2 fragCoord){
  const vec2 lo = vec2(-6.0, 0.0);
  const vec2 hi = vec2( 6.0, 8.0);
  vec2 sz = hi - lo;
  float sc = uResolution.y / sz.y;
  float cx = 0.5*(lo.x + hi.x);
  return vec2(
    (fragCoord.x - 0.5*uResolution.x)/sc + cx,
    fragCoord.y/sc + lo.y
  );
}

vec2 cdiv(vec2 a, vec2 b){
  float d = dot(b,b);
  return vec2((a.x*b.x+a.y*b.y)/d, (a.y*b.x-a.x*b.y)/d);
}

float asinh1(float x){
  return log(x + sqrt(x*x + 1.0));
}

// Exact hyperbolic distance to the geodesic with ideal endpoints ea, eb.
float signedDistGeodesic(float ea, float eb, vec2 z){
  float c = 0.5*(ea + eb);
  float r = 0.5*abs(eb - ea);
  float dx = z.x - c;
  return asinh1((dx*dx + z.y*z.y - r*r) / (2.0 * r * max(z.y, 1e-6)));
}

float distToVertical(float x0, vec2 z){
  return asinh1(abs(z.x - x0) / max(z.y, 1e-6));
}

void main(){
  float m  = max(uChildren, 2.0);
  float a  = max(uParam, 0.01);
  float hw = max(uThickness, 0.001);
  float logB = log2(m);
  float tW = m * a;                   // tile width = m*a

  vec2 fc = (vPos*0.5+0.5)*uResolution;
  vec2 p  = toWorld(fc);

  vec3 col = vec3(0.06);

  // x-axis
  float ax = 1.0 - smoothstep(0.0, 2.0*fwidth(p.y), abs(p.y));
  col = mix(col, vec3(0.85), ax);

  if(p.y > 0.0){
    float x = p.x, y = p.y;
    float eps = max(1e-6, fwidth(y));
    float yC  = max(y, eps);

    int   n = int(floor(log2(yC)/logB));
    float K = pow(m, float(-n));

    // Renormalized coords (pre-cap): tile in [0, tW] x [1, m]
    float xren = K*x;
    float yren = K*y;
    float cell = floor(xren/tW);
    float xmod = xren - cell*tW;       // in [0, tW)
    float ymod = yren;

    float yOrig = yren;                // save pre-cap state for edges
    float xmodOrig = xmod;

    // ── Theorem 5 cap geometry ──
    // Bottom vertices at (k*a, 1) for k = 0..m.
    // Geodesic segment k connects (k*a, 1) to ((k+1)*a, 1):
    //   semicircle center = ((k+0.5)*a, 0), radius^2 = a^2/4 + 1.
    float rb2 = a*a*0.25 + 1.0;
    float r0  = sqrt(rb2);

    bool  under = false;
    float dCap  = 1e10;

    for(int k = 0; k < MAX_CHILDREN; k++){
      if(float(k) >= m) break;
      float ck = (float(k)+0.5)*a;
      float dx = xmod - ck;
      float d2 = dx*dx + ymod*ymod;
      if(d2 < rb2) under = true;

      float ga = ck - r0, gb = ck + r0;
      float d  = abs(signedDistGeodesic(ga, gb, vec2(xmod, ymod)));
      dCap = min(dCap, d);
    }

    if(under){
      n -= 1;
      K = pow(m, float(-n));
      xren = K*x;
      yren = K*y;
      cell = floor(xren/tW);
      xmod = xren - cell*tW;
    }

    // ── 4-coloring (valid for any m) ──
    int h  = -n;
    int l  = int(cell);
    int pN = int(mod(float(h)+4096.0, 2.0));
    int pL = int(mod(float(l)+4096.0, 2.0));
    int id = pN*2 + pL;
    vec3 tc = color4(id);

    float fade = smoothstep(0.0, 3.0*eps, y);
    col = mix(col, tc, fade);

    // ── Edge lines (exact hyperbolic thickness) ──

    // Top edge: geodesic from (0, m) to (tW, m) in pre-cap cell coords
    float topR  = sqrt(tW*tW*0.25 + m*m);
    float dTop  = abs(signedDistGeodesic(tW*0.5-topR, tW*0.5+topR, vec2(xmodOrig, yOrig)));
    float pwTop = fwidth(dTop);
    float lTop  = 1.0 - smoothstep(hw-pwTop, hw+pwTop, dTop);

    // Vertical: geodesics at cell boundaries x = 0 and x = tW
    float dV  = min(distToVertical(0.0, vec2(xmod, yren)),
                    distToVertical(tW,  vec2(xmod, yren)));
    float pwV = fwidth(dV);
    float lV  = 1.0 - smoothstep(hw-pwV, hw+pwV, dV);

    // Bottom bumps: geodesic distance to cap arcs
    float pwC = fwidth(dCap);
    float lC  = 1.0 - smoothstep(hw-pwC, hw+pwC, dCap);

    float line = max(max(lTop, lV), lC);
    col = mix(col, vec3(0.15), line*fade);
  }

  gl_FragColor = vec4(col, 1.0);
}
